nodeLinker: node-modules

# Cache settings
enableGlobalCache: false
enableImmutableCache: false

# Allow non-immutable installs in CI/Cloud environments
enableImmutableInstalls: false

# Don't check for updates during install
enableProgressBars: false
